# inflator.toml syntax documentation: https://github.com/faretek1/inflator#inflator
name = 'base'
version = "v0.0.0"
username = "FAReTek1"

[dependencies]
string = "https://github.com/FAReTek1/string"
math = "https://github.com/FAReTek1/math"
